### ISSUE TITLE
upload Content

### ISSUE THREAD

**Issue by rabiul042** [rabiul042/academicbd#6]
Fix in such a way so that only departments of selected institution are being shown as dropdown instead of showing all the departments. Same goes for subjects.

**Comment by mdashraf7** [comment]
Still all the subject/courses are coming as dropdown menu. It is required to show only the courses relevant to the semester (level-term)

**Comment by rabiul042** [comment]
@mdashraf7 Please check this and give me the feedback.

**Comment by mdashraf7** [comment]
The way you have  resolved, it makes the issue more complex. Now for the same term, for all the departments, same subject/courses are showing at the user interface, although those are not relevant for all departments.

For example, from admin panel, **Nonwoven** course had been uploaded for **fabric engineering** department for **level 4 term 2**. But what happened, is, **Nonwoven** is showing in level 4 term 2, for all other departments!!! **Nonwoven** course is only applicable for **fabric engineering** department for **level 4 term 2**

**Comment by Mamba-dot** [comment]
The problem has been solved. Please check and give me feedback. @mdashraf7

**Comment by mdashraf7** [comment]
The issue has been resolved.
